version: '3.5'

services:
  postgres:
    container_name: identity_fort_postgres
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'

  mailhog:
    container_name: identity_fort_mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres:
